### ISSUE TITLE
After successful deployment ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by mattx264** [rpuls/medusajs-for-railway-boilerplate#2]
Hey,
Fresh new deployment but error ERR_TOO_MANY_REDIRECTS on front end store

**Comment by mattx264** [comment]
Issue was with db seed, there was no data in db.

**Comment by rpuls** [comment]
Hello, interesting. Where did you run this? On Railway ?
The fronend should be started with the `"wait": "node script/awaitBackendReady.js",` script, in order to ensure the backend has finished seeding the db the first time the project is run. On Railway it should be setup to do do this already, so I am curious how you started the project to get the error?
